#!/usr/bin/env python3
"""Build custom_components/sb_watch/frontend/sb-watch-panel.js.

The rule editor lives in ONE place: the SB Watch Card (../sb-watch-card/dist/
sb-watch-card.js). The sidebar panel hosts the same editor, so this script
copies the card's code under panel-private element names — the dashboard card
may be loaded on the same page, and a custom element name can be defined only
once — and appends the panel shell.

    python3 tools/build_panel.py            (run before every release)
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CARD = ROOT.parent / "sb-watch-card" / "dist" / "sb-watch-card.js"
OUT = ROOT / "custom_components" / "sb_watch" / "frontend" / "sb-watch-panel.js"
SHELL = ROOT / "tools" / "panel_shell.js"


def must(src: str, old: str, new: str) -> str:
    if src.count(old) != 1:
        sys.exit(f"build_panel: expected exactly one {old!r} in the card source, found {src.count(old)}")
    return src.replace(old, new)


def main() -> None:
    src = CARD.read_text()
    card_version = re.search(r'const VERSION = "([^"]+)";', src).group(1)
    version = json.loads((ROOT / "custom_components" / "sb_watch" / "manifest.json").read_text())["version"]
    src = must(src, 'const CARD = "sb-watch-card";', 'const CARD = "sb-watch-rules";')
    src = must(src, 'customElements.define("sb-watch-card-editor", SbWatchCardEditor);', 'customElements.define("sb-watch-rules-editor", SbWatchCardEditor);')
    src = must(src, 'return document.createElement("sb-watch-card-editor");', 'return document.createElement("sb-watch-rules-editor");')
    src = re.sub(r"window\.customCards = window\.customCards \|\| \[\];\nwindow\.customCards\.push\(\{.*?\}\);\n", "", src, count=1, flags=re.S)
    if "window.customCards" in src:
        sys.exit("build_panel: the customCards registration is still in the copy")
    src = re.sub(r"console\.info\(`%c SB-WATCH-CARD .*?\);\n", "", src, count=1, flags=re.S)
    # the panel is not a card: no "this card's" notify service to fall back on
    src = must(src, "To the rule's notify service, else this card's, else the one your other rules use, else a persistent notification.",
               "To the rule's notify service, else the one your other rules use, else a persistent notification.")
    shell = SHELL.read_text().replace("__VERSION__", version).replace("__CARD_VERSION__", card_version)
    OUT.write_text(
        f"// GENERATED by tools/build_panel.py — do not edit. sb_watch {version}; editor from sb-watch-card {card_version}.\n"
        + src.rstrip() + "\n\n" + shell
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({len(OUT.read_text().splitlines())} lines) — sb_watch {version}, card {card_version}")


if __name__ == "__main__":
    main()
